apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-service-dev
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/alexpermiakov/idp
      targetRevision: HEAD
      path: helm-charts/standard-service
      helm:
        releaseName: version-service
        values: |
          app:
            name: version-service
            image: 864992049050.dkr.ecr.us-west-2.amazonaws.com/idp/version:v1.0.0
            port: 8080
          resourceProfile: small
          replicaCount: 3
          ingress:
            enabled: true
            className: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/group.name: idp-services
            hosts:
              - host: ""
                paths:
                  - path: /version
                    pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: version-service-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

