apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexpermiakov/local-time-go-server
    targetRevision: main
    path: helm-charts/standard-service # Platform's golden chart
    helm:
      releaseName: time-service
      values: |
        app:
          name: time-service
          image: 864992049050.dkr.ecr.us-east-1.amazonaws.com/idp/localtime:sha-714f35e
          port: 1599

        resourceProfile: medium  # small, medium, or large

        replicaCount: 3

  destination:
    server: https://kubernetes.default.svc
    namespace: time-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

